//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServed
    {
        public int OrderId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual SalonData SalonData { get; set; }
        public virtual Service Service { get; set; }
    }
}
